### ISSUE TITLE
Subtheme issue

### ISSUE THREAD

**Issue by baisong** [i-amdroid/material_base#1]
Love this theme!

I'm trying to change the color scheme inside the `material_compile` starterkit subtheme.

Here's what I've done:

```
$ cd themes/material_base/starterkits/material_compile
$ npm install
$ vim sass/_variables.scss # change the primary and accent colors
```

...And here's what I get when I run `gulp`:

```
$ gulp
[16:00:33] Using gulpfile ../material_compile/gulpfile.js
[16:00:33] Starting 'sass'...
[16:00:33] Starting 'imagemin'...
[16:00:33] Finished 'imagemin' after 7.48 ms
[16:00:33] Starting 'watch'...
[16:00:33] Finished 'watch' after 9.22 ms
[16:00:33] gulp-imagemin: Minified 0 images
[16:00:33] /var/lib/gems/2.3.0/gems/compass-core-1.1.0.alpha.3/lib/compass/core/caniuse.rb:72: warning: circular argument reference - browsers
[16:00:33] NoMethodError:
[16:00:33] undefined method `has?' for Sass::Util:Module
Did you mean?  hash
               Hash
  Use --trace for backtrace.
[16:00:33] Finished 'sass' after 179 ms
[16:00:33] Starting 'autoprefixer'...
[16:00:33] Finished 'autoprefixer' after 1.67 ms
[16:00:33] Starting 'build'...
[16:00:33] Finished 'build' after 1.07 μs
[16:00:33] Starting 'default'...
[16:00:33] Finished 'default' after 1.39 μs
```

(And it hangs indefinitely without exiting)

Any tips for troubleshooting?

**Comment by i-amdroid** [comment]
Hi.

I can suggest:

1. Check Sass and Compass versions compatibility. Sass 3.5.x don't work with Compass 1.0.3 for me, I use Sass 3.4.x and Compass 1.0.3
2. Try to compile without Gulp with `sass --compass`
3. Check or better use absolute paths to base theme files in `styles.scss`
